# Generated by Django 4.0.6 on 2022-07-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classattendence', '0002_alter_student_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='roll_no',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='classattendence.student'),
        ),
    ]
