# Generated by Django 4.0.6 on 2022-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classattendence', '0003_alter_photo_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='dataset/'),
        ),
    ]
